export const GET_PROPERTY_DATA = "GET_PROPERTY_DATA";
export const LOADING = "LOADING";
export const ERROR = "ERROR";
export const FILTER_BY_SEARCH_QUERY = "FILTER_BY_SEARCH_QUERY";
export const FILTER_PROPERTY_DATA = "FILTER_PROPERTY_DATA";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE FROM FAVORITES";
